### ISSUE TITLE
Missing picorv32_retirq_insn() in irq_vec:

### ISSUE THREAD

**Issue by mkvenkit** [lawrie/tiny_soc#1]
https://github.com/lawrie/tiny_soc/blob/50898d65e62729057f25cf3a32d7fe1dc42609ea/examples/audio_song_player/start.S#L93

Is the ` irq_vec:` missing a  `picorv32_retirq_insn()`? It's done in `cleanup:` but not in the success case. I was using a portion your code and found it to hang till I added the return. 

Thanks for sharing your work!

**Comment by gundy** [comment]
Hi! :)  Can you clarify where you added the `retirq_insn`?  As far as I understand, and it's been a while since I looked at this, but the whole IRQ handler should run, right until the end point where the `retirq_insn()` is, all of the time..  in fact, it's kind of important that it does.  The first half (up until the instruction before `cleanup:` should be storing copies of all of the registers, then the irq handler is called, then `cleanup:` onwards restores the registers to their previous state before exiting from the irq handler)..    

I'm really curious though as to why things may have been breaking for you.  I do recall I had a few issues once because I had picorv configured in such a way that it didn't support the full complement of registers that were required.

**Comment by mkvenkit** [comment]
Hello,

Thanks for the response!

I added `picorv32_retirq_insn` right after `jalr` call:

```
	// call to C function
	beq zero, ra, cleanup  // if ra is a null pointer, don't jump to it
	jalr ra, ra, 0         // jump to [ra], and at the same time, load RA with return address

	// return 
	picorv32_retirq_insn()

cleanup:

	//addi sp, sp, -384
	addi sp, zero, 0

	/* restore registers */
	lw x1,   0*4(sp)
	picorv32_setq_insn(q0, x1)	// Q0
```
Without the above call, the processor was hanging. 

Also, I was not trying `tiny_soc` per se - I copied over `start.S` and `sections.ld` to a fresh picosoc project. Once I made the change above, I was able to implement a "button press" interrupt. 

Also, I am not an expert on assembly, so does the `cleanup:` section get executed every time? I had assumed it does so only in case of `ra` being `0`.

**Comment by gundy** [comment]
Given the fact that you're trying to apply this to a fresh picosoc project, it may be a similar issue to the one I was having a while ago:  https://github.com/cliffordwolf/picorv32/issues/86    -- please check that the configuration options you're using for picorv32 match those used in the project here - there are some pretty weird and subtle issues that can happen otherwise.   Apologies if you've already checked all of the options :)

BTW, I believe that the jalr instruction - or at least the 'subroutine' that it jumps to - will return to the instruction after jalr (ie. the `cleanup:` block) when it's finished.

D.

**Comment by mkvenkit** [comment]
Thanks for the issue link. I am setting `ENABLE_IRQ_QREGS = 1`. But I am probably doing something wrong elsewhere. I'll close this issue. Appreciate your prompt response!

**Comment by gundy** [comment]
> Thanks for the issue link. I am setting `ENABLE_IRQ_QREGS = 1`. But I am probably doing something wrong elsewhere. I'll close this issue. Appreciate your prompt response!

In my case, as well as enabling the QREGS, I needed to make sure that the memory allocated to the register file was actually large enough to accomodate them..   I don't think that was the case by default.   I'm sorry I haven't been much more help - it's been a while since I looked into this and my memory is fading a little now, although small pieces are starting to come back :)  Good luck; I know these kind of problems can be frustrating to find and fix, but it's very rewarding when you finally figure it out!!

**Comment by mkvenkit** [comment]
Thanks! It's been quite a learning experience for me, and *tiny_soc* is a great reference project.

**Comment by mkvenkit** [comment]
Hi @gundy, 

One more observation:

In `irq_vec` in [start.S](https://github.com/lawrie/tiny_soc/blob/master/examples/audio_song_player/start.S)

```
picorv32_setq_insn(q2, x1)  // q2 = ra
picorv32_setq_insn(q3, sp)  // q3 = stack pointer
```
But towards the end of the section...

```
picorv32_getq_insn(x1, q3)
picorv32_getq_insn(x2, q2)
```
Seems to me that q2 and q3 are flipped above.

In any case, this is the code that worked for me after some tweaks:

```
.balign 16
irq_vec:

	picorv32_setq_insn(q2, x1)  // q2 = ra
	picorv32_setq_insn(q3, sp)  // q3 = stack pointer

	// x2 is the stack pointer
	// stack normally is consumed from top downwards, but
	// irq handler uses stack right at bottom of stack range
	// (leaving top of stack for normal programs)..

	addi sp, zero, 0

//	lui sp, %hi(0)
//	addi sp, sp, %lo(0)

	picorv32_getq_insn(x1, q0)
	sw x1,   0*4(sp)            // Q0 = return address from IRQ vector

	picorv32_getq_insn(x1, q2)
	sw x1,   1*4(sp)            // Q2 = X1 = RA

	picorv32_getq_insn(x1, q3)
	sw x1,   2*4(sp)            // Q3 = SP

	sw x3,   3*4(sp)
	sw x4,   4*4(sp)
	sw x5,   5*4(sp)
	sw x6,   6*4(sp)
	sw x7,   7*4(sp)
	sw x8,   8*4(sp)
	sw x9,   9*4(sp)
	sw x10, 10*4(sp)
	sw x11, 11*4(sp)
	sw x12, 12*4(sp)
	sw x13, 13*4(sp)
	sw x14, 14*4(sp)
	sw x15, 15*4(sp)
	sw x16, 16*4(sp)
	sw x17, 17*4(sp)
	sw x18, 18*4(sp)
	sw x19, 19*4(sp)
	sw x20, 20*4(sp)
	sw x21, 21*4(sp)
	sw x22, 22*4(sp)
	sw x23, 23*4(sp)
	sw x24, 24*4(sp)
	sw x25, 25*4(sp)
	sw x26, 26*4(sp)
	sw x27, 27*4(sp)
	sw x28, 28*4(sp)
	sw x29, 29*4(sp)
	sw x30, 30*4(sp)
	sw x31, 31*4(sp)

	/* call interrupt handler C function */

	// arg1 = pointer to stored registers
	mv x11, sp

	// arg0 = interrupt type bitmask
	picorv32_getq_insn(x10, q1)					// Q1 contains bitmask of interrupts that were triggered

	// make some room on the stack for the interrupt handler
	addi sp, sp, 384   // 128 bytes for register file, 256 bytes for interrupt handler stack

	/* 
	// load irq handler address to x1 (ra)
	la ra, irq_handler

	// call to C function
	beq zero, ra, cleanup  // if ra is a null pointer, don't jump to it
	jalr ra, ra, 0         // jump to [ra], and at the same time, load RA with return address
	*/
	jal ra, irq_handler

cleanup:

	//addi sp, sp, -384
	addi sp, zero, 0

	/* restore registers */
	lw x1,   0*4(sp)
	picorv32_setq_insn(q0, x1)	// Q0

	lw x1,   1*4(sp)
	picorv32_setq_insn(q3, x1)   // RA

	lw x1,   2*4(sp)
	picorv32_setq_insn(q2, x1)   // SP

	picorv32_getq_insn(x1, q2)
	picorv32_getq_insn(x2, q3)

	lw x3,   3*4(sp)	
	lw x4,   4*4(sp)
	lw x5,   5*4(sp)
	lw x6,   6*4(sp)
	lw x7,   7*4(sp)
	lw x8,   8*4(sp)
	lw x9,   9*4(sp)
	lw x10, 10*4(sp)
	lw x11, 11*4(sp)
	lw x12, 12*4(sp)
	lw x13, 13*4(sp)
	lw x14, 14*4(sp)
	lw x15, 15*4(sp)
	lw x16, 16*4(sp)
	lw x17, 17*4(sp)
	lw x18, 18*4(sp)
	lw x19, 19*4(sp)
	lw x20, 20*4(sp)
	lw x21, 21*4(sp)
	lw x22, 22*4(sp)
	lw x23, 23*4(sp)
	lw x24, 24*4(sp)
	lw x25, 25*4(sp)
	lw x26, 26*4(sp)
	lw x27, 27*4(sp)
	lw x28, 28*4(sp)
	lw x29, 29*4(sp)
	lw x30, 30*4(sp)
	lw x31, 31*4(sp)

	picorv32_retirq_insn()
```

For some reason, I have to restore `x2` and `x1` before the rest of the registers. (Actually the culprit seems to be `x8`, the frame pointer.)
